[package]
name = "slipway_registry"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.10.2"
once_cell = "1.21.3"
prometheus = "0.14.0"
regex = "1.11.1"
time = "0.3.41"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
